<form  id="form1" method="post" action="">
	<input type="hidden" name="guardar" value="1"/>
	<p>Titulo:<br />
	<input type="texto" name="titulo" value="<?php if(isset($this->datos['titulo'])) echo $this->datos['titulo']; ?>"/></p>
	<p>Contenido:<br />
	<textarea name="contenido"><?php if(isset($this->datos['comentario'])) echo $this->datos['comentario']; ?></textarea></p>
	<p><input type="submit" class="button" value="Guardar"></p>
</form>
